name: artifact

on: [push]

env: 
  ARTIFACT_NAME= "MERA_WALA_ARTIFACT"
  
jobs:
  main:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
