name: Environment_Variables

env:
  ENV_AT_WORKSPACE: "workspace env variable"
  OVERRIDE_ENV: "workspace Oenv variable"
 
on: push

jobs:
  env_test:
  
    env:
      ENV_AT_JOB: "job env variable"
      OVERRIDE_ENV: "job Oenv variable"
      
    runs-on: ubuntu-latest
    
    steps:
      - name: step print env
        env:
          ENV_AT_STEP: "step env variable"
          OVERRIDE_ENV: "step Oenv variable"
        run: | 
          echo "$ENV_AT_WORKSPACE"
          echo "-----------------
          echo "$ENV_AT_JOB"
          echo "-----------------          
          echo "$ENV_AT_STEP"                    
          echo "-----------------
          echo "$OVERRIDE_ENV"                    
          echo "-----------------
